### ISSUE TITLE
Remove stance check

### ISSUE THREAD

**Issue by jrbudda** [possi/MineVive#1]
Hey there, I'm updating Automat's minecrift-vive and there's some other things I think need to change for a compatible server.
- The 'stance' check should be removed from C03PacketPlayer, the client mod now allows ducking and crawling.
- The C07PacketPlayerDigging processing has some distances checks in it, I'm not sure if they're just filters for performance but there have been reports of phantom blocks out of sync between players, this or something else might be doing it. The blocks can be significantly far away from the packet entity due to extended reach plus the roomscale locomotion.

Also we're trying to compile all the instuctions at the following wiki if you have any input.
https://www.reddit.com/r/Vive/wiki/minecrift_for_vive

Thanks!

**Comment by possi** [comment]
First of all: Thanks for your really great work on Minecrift! I'm so happy with the locomotion-options you introduced.

Could you do me a favor and join us at the Multiplayer Discord-Chat (mentioned in the wiki)? There are many interested Vivecraft users. I would love if we're able to improve Multiplayer-Support together.

Now about your change request. Sadly I'm not that into the Minecraft protocol, so you have to support me.
- I'm not sure what you mean about stance.
  The whole teleporting locomotion counts as a cheat to the server, why you have to raise the invalid-movement-threshold. What else needs to be changed?
- I've experiences such phantom blocks multiple times myself. But it seems not to be a distance problem, as I was able to continue digging behind the phantom block without moving. I'm guessing a timing issue, maybe caused by the performance of my own server.

**Comment by jrbudda** [comment]
Stance is your height from the floor, the game (server) expects it always to be a certain value (only really changes when sleeping). In vivecraft it now can change with your head movement. There's a check in the C03 processing for it just like there is for teleporting. I'm guessing spigot doesnt have a config option for it so it might have to be changed in the MC code.

Really not sure about the phantom blocks either, I just noticed something in that packet that may be the cause.

**Comment by possi** [comment]
I found the stance check, but I have no idea how this effects anything. Everything works fine as far as i can tell.
Can you tell me how to reproduce anything blocked by this check?

Also I tried reproducing the phantom blocks on a server in local network. Everything works fine, so it really seems to be affected by server performance.

**Comment by jrbudda** [comment]
ok thanks. What would trigger the stance check would be trying to crawl thru a 1-high block gap.

**Comment by possi** [comment]
Shouldn't be needed anymore.
- Crouching one block height isn't intended on MP
- Sleeping works without error.
